# Generated by Django 2.2.4 on 2019-09-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenlabcab',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
