# Generated by Django 2.2.1 on 2019-06-28 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenlabcab',
            name='nombre_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examenlabcab',
            name='codigoExam',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examenlabcab',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='examenlabcab',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examenlabcab',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admision.Paciente'),
        ),
        migrations.AlterField(
            model_name='examenlabcab',
            name='resultado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='examenlabdet',
            name='codigoExam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Laboratorio.ExamenLabCab'),
        ),
        migrations.AlterField(
            model_name='examenlabdet',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examenlabdet',
            name='rangoReferencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examenlabdet',
            name='resultadoObtenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tipoexamen',
            name='codigoTExam',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
