# Generated by Django 2.2.4 on 2019-11-16 18:19

import apps.Consultorio.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrador', '0001_initial'),
        ('Admision', '0001_initial'),
        ('Laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroRecibo', models.CharField(blank=True, max_length=15, null=True)),
                ('fechaSeparacion', models.DateField(auto_now_add=True)),
                ('fechaAtencion', models.DateField(validators=[apps.Consultorio.validators.fechaAtencion])),
                ('estadoCita', models.CharField(blank=True, max_length=10, null=True)),
                ('responsable', models.CharField(blank=True, max_length=50, null=True)),
                ('exonerado', models.BooleanField(default=False)),
                ('estReg', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citasE', to='Administrador.Especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citasM', to='Administrador.Personal')),
                ('numeroHistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='Admision.Historia')),
            ],
        ),
        migrations.CreateModel(
            name='Triaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.FloatField(validators=[apps.Consultorio.validators.valoresnegativos])),
                ('peso', models.FloatField(validators=[apps.Consultorio.validators.valoresnegativos])),
                ('temperatura', models.FloatField(validators=[apps.Consultorio.validators.valoresnegativos])),
                ('frecuenciaR', models.IntegerField(validators=[apps.Consultorio.validators.valoresnegativos])),
                ('frecuenciaC', models.IntegerField(validators=[apps.Consultorio.validators.valoresnegativos])),
                ('presionArt', models.TextField(max_length=7)),
                ('fechaReg', models.DateField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Cita')),
                ('numeroHistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triajes', to='Admision.Historia')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('medico', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaA', models.DateField(validators=[apps.Consultorio.validators.fechaAtencion])),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('estadoOrden', models.CharField(blank=True, max_length=10, null=True)),
                ('numeroHistoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='Admision.Historia')),
                ('tipoExam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Laboratorio.TipoExamen')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('triaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Consultorio.Triaje')),
                ('motivoConsulta', models.TextField()),
                ('apetito', models.CharField(max_length=100)),
                ('orina', models.CharField(max_length=100)),
                ('deposiciones', models.CharField(max_length=100)),
                ('examenFisico', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnostico', models.TextField(max_length=300)),
                ('tratamiento', models.TextField(max_length=300)),
                ('ordenExam', models.TextField(blank=True, max_length=200, null=True)),
                ('proximaCita', models.DateField(blank=True, null=True)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Personal')),
                ('numeroHistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='Admision.Historia')),
            ],
        ),
    ]
