# Generated by Django 2.2.4 on 2019-09-22 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admision', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroRecibo', models.CharField(max_length=15)),
                ('fechaSeparacion', models.DateField(blank=True, null=True)),
                ('fechaAtencion', models.DateField()),
                ('estadoCita', models.CharField(blank=True, max_length=10, null=True)),
                ('estReg', models.BooleanField(default=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citasM', to=settings.AUTH_USER_MODEL)),
                ('numeroHistoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='Admision.Historia')),
            ],
        ),
        migrations.CreateModel(
            name='Triaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.FloatField()),
                ('peso', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('frecuenciaR', models.IntegerField()),
                ('frecuenciaC', models.IntegerField()),
                ('presionArt', models.TextField()),
                ('fechaReg', models.DateField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Cita')),
                ('numeroHistoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triajes', to='Admision.Historia')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaEntrada', models.DateTimeField(blank=True, null=True)),
                ('horaSalida', models.DateTimeField(blank=True, null=True)),
                ('motivoConsulta', models.TextField(blank=True, null=True)),
                ('apetito', models.CharField(blank=True, max_length=100, null=True)),
                ('orina', models.CharField(blank=True, max_length=100, null=True)),
                ('deposiciones', models.CharField(blank=True, max_length=100, null=True)),
                ('examenFisico', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnostico', models.TextField(blank=True, max_length=300, null=True)),
                ('tratamiento', models.TextField(blank=True, max_length=300, null=True)),
                ('proximaCita', models.DateField(blank=True, null=True)),
                ('estadoAtencion', models.CharField(blank=True, max_length=1, null=True)),
                ('motivoAnulacion', models.TextField(blank=True, null=True)),
                ('estReg', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('numeroHistoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='Admision.Historia')),
                ('triaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Triaje')),
            ],
        ),
    ]
