# Generated by Django 2.2.4 on 2019-11-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='numeroHistoria',
        ),
    ]
