# Generated by Django 2.2.4 on 2019-12-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='dni',
            field=models.CharField(blank=True, error_messages={'unique': 'Este DNI ya ha sido registrado.'}, max_length=15, null=True, unique=True),
        ),
    ]
