# Generated by Django 2.2.4 on 2019-12-10 23:56

import apps.Admision.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='numeroHistoria',
            field=models.IntegerField(default=apps.Admision.models.autoincrementar, editable=False),
        ),
    ]
