# Generated by Django 2.2.4 on 2019-12-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admision', '0002_auto_20191216_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='dni',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='nombres',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
